name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
 pull_request:
   types:
     - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v
